# Generated by Django 4.0.5 on 2022-06-29 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appProductGroup', '0001_initial'),
        ('appProductCategory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=255, verbose_name='Цвет')),
            ],
            options={
                'verbose_name': 'Цвет',
                'verbose_name_plural': 'Цвета',
            },
        ),
        migrations.CreateModel(
            name='ProductFitting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fitting', models.CharField(max_length=255, verbose_name='Фурнитура')),
            ],
            options={
                'verbose_name': 'Фурнитура',
                'verbose_name_plural': 'Фурнитруа',
            },
        ),
        migrations.CreateModel(
            name='ProductMakeTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make_time', models.CharField(max_length=255, verbose_name='Время изготовления')),
            ],
            options={
                'verbose_name': 'Время изготовления',
                'verbose_name_plural': 'Время изготовления',
            },
        ),
        migrations.CreateModel(
            name='ProductMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(max_length=255, verbose_name='Материал')),
            ],
            options={
                'verbose_name': 'Материал',
                'verbose_name_plural': 'материалы',
            },
        ),
        migrations.CreateModel(
            name='ProductItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('product_price', models.CharField(max_length=255, verbose_name='Цена')),
                ('product_old_price', models.CharField(default='-', max_length=255, verbose_name='Старая цена')),
                ('product_size', models.CharField(max_length=255, verbose_name='Размер')),
                ('product_description', models.TextField(verbose_name='Описание')),
                ('product_img_main', models.ImageField(upload_to='product_img/')),
                ('product_img_main_alt', models.CharField(max_length=255, verbose_name='Альтернативный текст фото')),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appProductCategory.productcategory', verbose_name='Категория товара')),
                ('product_color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appProductItem.productcolor', verbose_name='Цвет')),
                ('product_fitting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='appProductItem.productfitting', verbose_name='Фурнитура')),
                ('product_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appProductGroup.productgroup', verbose_name='Группа товара')),
                ('product_make_time', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appProductItem.productmaketime', verbose_name='Время изготовления')),
                ('product_material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appProductItem.productmaterial', verbose_name='Материал')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='ProductImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_small', models.ImageField(upload_to='product_img/', verbose_name='Маленькая картинка 100х100')),
                ('alt_small', models.CharField(max_length=200, verbose_name='Альтернативный текст маленькой картинки')),
                ('img_medium', models.ImageField(upload_to='product_img/', verbose_name='Средняя картинка 330х330')),
                ('alt_medium', models.CharField(max_length=200, verbose_name='Альтернативный текст маленькой картинки')),
                ('img_big', models.ImageField(upload_to='product_img/', verbose_name='Большая картинка')),
                ('alt_big', models.CharField(max_length=200, verbose_name='Альтернативный текст маленькой картинки')),
                ('img_binding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appProductItem.productitem', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Картинка товара',
                'verbose_name_plural': 'Картинки товара',
            },
        ),
    ]
